// <auto-generated />
namespace DatabaseNamespace.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class intialone1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intialone1));
        
        string IMigrationMetadata.Id
        {
            get { return "201802041737593_intialone1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
